<?php
/**
 * Created by PhpStorm.
 * User: aceplus
 * Date: 18/07/19
 * Time: 10:40
 */

namespace Module\Infrastructure\Provider;


use Carbon\Laravel\ServiceProvider;

class RepositoryServiceProvider extends ServiceProvider
{
    public function boot()
    {
        // TODO: Change the autogenerated stub
    }

    public function register()
    {
        // TODO: Change the autogenerated stub
    }
}